Repository Yoast/PHPUnit-Polyfills, pull requests merged in 2021-09, with the labels that each got.

#52 README: various small updates / add FAQ about setup-php
  README.md
Labels: Type: documentation

#53 Composer: update dev dependency
  composer.json
Labels: Type: chores/QA

#54 Fix command name used to generate autoload files
  README.md
Labels: Type: documentation, community-patch

#56 PHPUnit: update configuration
  phpunit.xml.dist
Labels: yoastcs/qa, Type: chores/QA
