Repository Yoast/PHPUnit-Polyfills, pull requests merged in 2021-06, with the labels that each got.

#15 CI: switch to GitHub Actions
  .gitattributes
  .github/workflows/cs.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: yoastcs/qa

#16 README: add FAQ section covering functionality removed from PHPUnit
  README.md
Labels: documentation

#19 Allow for using the polyfills on PHP 5.4
  .github/workflows/test.yml
  README.md
  composer.json
  phpunitpolyfills-autoload.php
  src/Polyfills/ExpectPHPException.php
  tests/Helpers/AssertAttributesHelperTest.php
  tests/Polyfills/ExpectExceptionMessageMatchesTest.php
  tests/Polyfills/ExpectExceptionTest.php
  tests/TestCases/TestCaseTestTrait.php
  tests/TestListeners/TestListenerTest.php
Labels: enhancement, yoastcs/qa

#20 XTestCase: set to lowest possible visibility
  src/TestCases/XTestCase.php
  tests/TestCases/XTestCaseTest.php
Labels: bug, yoastcs/qa

#21 TestCaseTestTrait: add missing tests
  tests/TestCases/TestCaseTestTrait.php
Labels: yoastcs/qa

#22 Tests: add bootstrap file
  phpunit.xml.dist
  phpunitpolyfills-autoload.php
  tests/Polyfills/ExpectExceptionTest.php
  tests/TestListeners/TestListenerTest.php
  tests/bootstrap.php
Labels: yoastcs/qa

#23 CI/QA: add experimental build against PHPUnit 10.0 (unreleased)
  .github/workflows/test.yml
Labels: yoastcs/qa

#24 AssertFileDirectoryTest: allow for running the tests on PHPUnit 10.0.0
  tests/Polyfills/AssertFileDirectoryTest.php
Labels: yoastcs/qa

#25 TestListenerTest: fix PHPUnit 10.0.0 compatibility
  tests/TestListeners/TestListenerTest.php
Labels: yoastcs/qa

#26 ExpectExceptionTest: fix PHPUnit 10.0.0 compatibility
  tests/Polyfills/ExpectExceptionTest.php
Labels: yoastcs/qa

#18 Handle strings containing empty strings assertions
  src/Polyfills/AssertStringContains.php
  tests/Polyfills/AssertStringContainsTest.php
Labels: community-patch, enhancement, yoastcs/qa

#27 New AssertClosedResource trait: polyfill the `Assert::assertIs[Not]ClosedResource()` methods
  .phpcs.xml.dist
  README.md
  phpunit.xml.dist
  phpunitpolyfills-autoload.php
  src/Helpers/ResourceHelper.php
  src/Polyfills/AssertClosedResource.php
  src/Polyfills/AssertClosedResource_Empty.php
  src/TestCases/TestCasePHPUnitGte8.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  tests/Polyfills/AssertClosedResourceBzip2Test.php
  tests/Polyfills/AssertClosedResourceCurlTest.php
  tests/Polyfills/AssertClosedResourceDirTest.php
  tests/Polyfills/AssertClosedResourceEnchantTest.php
  tests/Polyfills/AssertClosedResourceFileTest.php
  tests/Polyfills/AssertClosedResourceFinfoTest.php
  tests/Polyfills/AssertClosedResourceGdTest.php
  tests/Polyfills/AssertClosedResourceNotResourceTest.php
  tests/Polyfills/AssertClosedResourceProcessTest.php
  tests/Polyfills/AssertClosedResourceShmopTest.php
  tests/Polyfills/AssertClosedResourceTestCase.php
  tests/Polyfills/AssertClosedResourceWddxTest.php
  tests/Polyfills/AssertClosedResourceXmlParserTest.php
  tests/Polyfills/AssertClosedResourceZipTest.php
  tests/Polyfills/AssertClosedResourceZlibTest.php
  tests/Polyfills/Fixtures/test.tar.bz2
  tests/Polyfills/Fixtures/test.tar.gz
  tests/Polyfills/Fixtures/test.txt
  tests/Polyfills/Fixtures/test.zip
  tests/TestCases/TestCaseTestTrait.php
Labels: enhancement, yoastcs/qa

#29 README: various improvements
  README.md
Labels: documentation

#30 README: add links to the PHPUnit documentation
  README.md
Labels: documentation

#28 Polyfill for equalTo constraint specializations
  README.md
  phpunitpolyfills-autoload.php
  src/Polyfills/EqualToSpecializations.php
  src/Polyfills/EqualToSpecializations_Empty.php
  src/TestCases/TestCasePHPUnitGte8.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  tests/Polyfills/EqualToSpecializationsTest.php
  tests/TestCases/TestCaseTestTrait.php
Labels: community-patch, enhancement

#31 GH Actions: expand the test matrix
  .github/workflows/test.yml
Labels: yoastcs/qa

#32 ResourceHelper: minor PHP cross-version compatibility fix
  src/Helpers/ResourceHelper.php
Labels: yoastcs/qa

#33 AssertClosedResource/ResourceHelper: add extra test
  tests/Polyfills/AssertClosedResourceNotResourceTest.php
Labels: yoastcs/qa

#34 GH Actions: no need to lint twice
  .github/workflows/test.yml
Labels: yoastcs/qa

#35 Documentation: minor improvement to inline docs
  src/Polyfills/AssertIsType.php
Labels: yoastcs/qa

#36 Add polyfills for the PHP 7.0 `TypeError` and `Error` classes
  .github/workflows/test.yml
  .phpcs.xml.dist
  composer.json
  phpunitpolyfills-autoload.php
  src/Exceptions/Error.php
  src/Exceptions/TypeError.php
Labels: enhancement, yoastcs/qa

#37 PHPCS: use PHPCompatibility proper, not PHPCompatibilityWP
  .phpcs.xml.dist
  src/Polyfills/AssertIsType.php
Labels: yoastcs/qa

#38 AssertObjectEquals trait: polyfill the Assert::assertObjectEquals() method
  .phpcs.xml.dist
  README.md
  composer.json
  phpunitpolyfills-autoload.php
  src/Exceptions/InvalidComparisonMethodException.php
  src/Polyfills/AssertObjectEquals.php
  src/Polyfills/AssertObjectEquals_Empty.php
  src/TestCases/TestCasePHPUnitGte8.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php
  tests/Polyfills/AssertObjectEqualsTest.php
  tests/Polyfills/Fixtures/ChildValueObject.php
  tests/Polyfills/Fixtures/ValueObject.php
  tests/Polyfills/Fixtures/ValueObjectNoReturnType.php
  tests/Polyfills/Fixtures/ValueObjectUnion.php
  tests/Polyfills/Fixtures/ValueObjectUnionNoReturnType.php
  tests/TestCases/TestCaseTestTrait.php
Labels: Type: enhancement, yoastcs/qa

#39 AssertObjectEquals: improve "not boolean return value" error message
  .phpcs.xml.dist
  src/Polyfills/AssertObjectEquals.php
  tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php
  tests/Polyfills/AssertObjectEqualsTest.php
  tests/Polyfills/Fixtures/ValueObject.php
  tests/Polyfills/Fixtures/ValueObjectNoReturnType.php
Labels: Type: chores/QA, Type: enhancement, yoastcs/qa

#40 Autoloader: minor simplification
  phpunitpolyfills-autoload.php
Labels: Type: chores/QA, yoastcs/qa

#41 Changelog for the release of version 1.0.0
  CHANGELOG.md
Labels: Type: documentation, yoastcs/qa

#43 README: minor updates
  README.md
Labels: Type: documentation, yoastcs/qa

#44 GH Actions: set error reporting to E_ALL
  .github/workflows/test.yml
Labels: Type: chores/QA, yoastcs/qa
