Repository Yoast/PHPUnit-Polyfills, pull requests merged in 2024-09, with the labels that each got.

#184 PHPStan: minor simplification in the config file
  phpstan.neon.dist
Labels: Type: chores/QA

#187 README: add expectDeprecation*() et al to FAQ > Removed functionality
  README.md
Labels: Type: documentation

#188 1.x | Minor updates for start of 3.x branch
  .github/RELEASE-CHECKLIST.md
  README.md
  composer.json
Labels: Type: documentation

#189 2.x | Tests: add attributes for annotations
  src/TestCases/XTestCase.php
  tests/Exceptions/InvalidComparisonMethodExceptionTest.php
  tests/Helpers/AssertAttributesHelperTest.php
  tests/Polyfills/AssertClosedResourceBzip2Test.php
  tests/Polyfills/AssertClosedResourceCurlTest.php
  tests/Polyfills/AssertClosedResourceDirTest.php
  tests/Polyfills/AssertClosedResourceEnchantTest.php
  tests/Polyfills/AssertClosedResourceFileTest.php
  tests/Polyfills/AssertClosedResourceFinfoTest.php
  tests/Polyfills/AssertClosedResourceGdTest.php
  tests/Polyfills/AssertClosedResourceNotResourceTest.php
  tests/Polyfills/AssertClosedResourceProcessTest.php
  tests/Polyfills/AssertClosedResourceShmopTest.php
  tests/Polyfills/AssertClosedResourceWddxTest.php
  tests/Polyfills/AssertClosedResourceXmlParserTest.php
  tests/Polyfills/AssertClosedResourceZipTest.php
  tests/Polyfills/AssertClosedResourceZlibTest.php
  tests/Polyfills/AssertEqualsSpecializationsTest.php
  tests/Polyfills/AssertFileEqualsSpecializationsTest.php
  tests/Polyfills/AssertIgnoringLineEndingsTest.php
  tests/Polyfills/AssertIsListTest.php
  tests/Polyfills/AssertIsTypeTest.php
  tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php
  tests/Polyfills/AssertObjectEqualsTest.php
  tests/Polyfills/AssertObjectPropertyTest.php
  tests/Polyfills/AssertStringContainsTest.php
  tests/Polyfills/AssertionRenamesTest.php
  tests/Polyfills/EqualToSpecializationsTest.php
  tests/Polyfills/ExpectExceptionMessageMatchesTest.php
  tests/Polyfills/ExpectExceptionObjectTest.php
  tests/TestCases/TestCaseTest.php
  tests/TestCases/TestCaseTestTrait.php
  tests/TestCases/XTestCaseTest.php
  tests/TestListeners/Fixtures/FailurePHPUnitGte7.php
  tests/TestListeners/Fixtures/IncompletePHPUnitGte7.php
  tests/TestListeners/Fixtures/RiskyPHPUnitGte7.php
  tests/TestListeners/Fixtures/SkippedPHPUnitGte7.php
  tests/TestListeners/Fixtures/SuccessPHPUnitGte7.php
  tests/TestListeners/Fixtures/TestErrorPHPUnitGte7.php
  tests/TestListeners/Fixtures/WarningPHPUnitGte7.php
  tests/TestListeners/TestListenerTest.php
Labels: Type: chores/QA

#190 README: update links to PHPUnit docs
  README.md
Labels: Type: documentation

#191 2.x | GH Actions: remove the trial run against PHPUnit 11
  .github/workflows/test.yml
Labels: Type: chores/QA

#192 3.0 | Drop support for PHP < 7.0
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .phpcs.xml.dist
  README.md
  composer.json
  phpunitpolyfills-autoload.php
  src/Exceptions/Error.php
  src/Exceptions/TypeError.php
  src/Polyfills/AssertObjectEquals.php
  tests/Polyfills/AssertIgnoringLineEndingsTest.php
  tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php
  tests/Polyfills/AssertObjectEqualsTest.php
  tests/Polyfills/AssertObjectPropertyTest.php
  tests/Polyfills/Fixtures/ValueObject.php
  tests/Polyfills/Fixtures/ValueObjectNoReturnType.php
  tests/Polyfills/Fixtures/ValueObjectNullableReturnType.php
  tests/Polyfills/Fixtures/ValueObjectUnionReturnType.php
  tests/TestCases/TestCaseTestTrait.php
Labels: Type: breaking change, Type: chores/QA, Feature: polyfills

#193 3.0 | Drop support for PHPUnit < 6.4
  .github/workflows/test.yml
  README.md
  composer.json
  phpunitpolyfills-autoload.php
  src/Polyfills/AssertStringContains.php
  src/Polyfills/ExpectExceptionObject.php
  src/Polyfills/ExpectExceptionObject_Empty.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  src/TestListeners/TestListenerDefaultImplementationPHPUnitLte5.php
  tests/Polyfills/AssertClosedResourceNotResourceTest.php
  tests/Polyfills/AssertClosedResourceShmopTest.php
  tests/Polyfills/AssertClosedResourceTestCase.php
  tests/Polyfills/AssertIgnoringLineEndingsTest.php
  tests/Polyfills/AssertIsListTest.php
  tests/Polyfills/AssertObjectEqualsTest.php
  tests/Polyfills/AssertObjectPropertyTest.php
  tests/Polyfills/AssertStringContainsTest.php
  tests/Polyfills/ExpectExceptionMessageMatchesTest.php
  tests/Polyfills/ExpectExceptionObjectTest.php
  tests/TestCases/TestCaseTestTrait.php
  tests/TestListeners/TestListenerTest.php
  tests/bootstrap.php
Labels: Type: breaking change, Type: chores/QA, Feature: polyfills, Feature: testlistener

#194 Drop support for the `AssertAttributeHelper`
  README.md
  phpunitpolyfills-autoload.php
  src/Helpers/AssertAttributeHelper.php
  src/TestCases/TestCasePHPUnitGte8.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  tests/Helpers/AssertAttributesHelperTest.php
  tests/Helpers/Fixtures/ClassWithProperties.php
Labels: Type: breaking change, Feature: helpers

#195 PHPUnit 11.3.1 | AssertIsList: sync error message with upstream
  src/Polyfills/AssertIsList.php
  tests/Polyfills/AssertIsListTest.php
Labels: Type: enhancement, Feature: polyfills

#197 PHPUnit 11 | Make select methods `protected`
  src/Polyfills/ExpectExceptionMessageMatches.php
Labels: Type: breaking change, Feature: polyfills

#198 PHPUnit 11 | AssertArrayWithListKeys trait: polyfill the Assert::assertArrayIsEqualToArrayOnlyConsideringListOfKeys() et al methods
  README.md
  phpunitpolyfills-autoload.php
  src/Polyfills/AssertArrayWithListKeys.php
  src/Polyfills/AssertArrayWithListKeys_Empty.php
  src/TestCases/TestCasePHPUnitGte8.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  tests/Polyfills/AssertArrayWithListKeysTest.php
  tests/TestCases/TestCaseTestTrait.php
Labels: Type: enhancement, Feature: polyfills

#200 PHPUnit 11 | ExpectUserDeprecationtrait: polyfill the TestCase::expectUserDeprecation*() methods
  .github/workflows/test.yml
  README.md
  composer.json
  phpstan.neon.dist
  phpunit10.xml.dist
  phpunitpolyfills-autoload.php
  src/Polyfills/ExpectUserDeprecation.php
  src/Polyfills/ExpectUserDeprecation_Empty.php
  src/TestCases/TestCasePHPUnitGte8.php
  src/TestCases/TestCasePHPUnitLte7.php
  src/TestCases/XTestCase.php
  tests/Polyfills/ExpectUserDeprecationTest.php
  tests/TestCases/TestCaseTestTrait.php
Labels: Type: enhancement, Feature: polyfills

#201 Changelog for the 1.1.2 release
  CHANGELOG.md
  phpunitpolyfills-autoload.php
Labels: Type: documentation

#202 Changelog for the 2.0.2 release
  CHANGELOG.md
  phpunitpolyfills-autoload.php
Labels: Type: documentation

#203 Changelog for the 3.0.0 release and other documentation updates
  .github/RELEASE-CHECKLIST.md
  CHANGELOG.md
  README.md
  phpunitpolyfills-autoload.php
Labels: Type: documentation
